In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.4'

## Create & Read

#### 1D Array



In [7]:
arr1 = np.array([1, 2, 3, 4, 5])

arr1

array([1, 2, 3, 4, 5])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1.dtype

dtype('int64')

In [10]:
arr1.size


5

In [11]:
arr1.ndim

1

In [12]:
arr1.shape

(5,)

#### 2D Array

In [21]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape  #(row, col)

(2, 3)

In [22]:
arr2.size

6

#### 3D ARRAY

In [24]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [25]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
arr3.ndim

3

In [27]:
arr3.shape

(1, 3, 3)

#### Create Random Array

In [28]:
randArr = np.random.rand(3, 2, 3)

In [29]:
randArr

array([[[0.97398365, 0.71158227, 0.67981762],
        [0.42970342, 0.6481527 , 0.49375144]],

       [[0.45908825, 0.25953254, 0.45199837],
        [0.81176868, 0.60246047, 0.49475233]],

       [[0.69795292, 0.7569205 , 0.83794445],
        [0.52031606, 0.23831015, 0.83307166]]])

In [32]:
zeros = np.zeros((3, 2, 3))

In [33]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
 zeros.ndim

3

In [35]:
full = np.full((3, 2, 3), 9)

In [36]:
ones = np.ones((3, 2, 3))

In [37]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr3[0][0][0]


np.int64(1)

In [40]:
arr3[0, 0, 0]

np.int64(1)

#### Update & Delete

In [41]:
a1 = np.random.rand(2, 3, 2)

In [42]:
a2 = np.random.rand(2, 3, 2)
np.add(a1, a2)

array([[[1.8203128 , 1.09080076],
        [0.15526765, 0.64414406],
        [0.99639284, 1.41622023]],

       [[0.71746818, 1.08199949],
        [0.79443018, 0.17988569],
        [1.02381109, 1.44882438]]])

In [43]:
np.subtract(a1, a2)

array([[[-0.15292093, -0.4573591 ],
        [-0.02141918,  0.38715688],
        [-0.17572743,  0.55202827]],

       [[ 0.18198027,  0.1189461 ],
        [ 0.31861453, -0.1023493 ],
        [-0.49256654, -0.11983862]]])

In [44]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)


In [45]:
sqrt

np.float64(5.0)

In [46]:
log

np.float64(3.2188758248682006)

In [47]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
arr3[0, 0, 1] = 500

In [49]:
arr3

array([[[  1, 500,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [50]:
arr3.sort()

In [51]:
arr3

array([[[  1,   3, 500],
        [  4,   5,   6],
        [  7,   8,   9]]])

#### NEW ARRAY

In [52]:
new_arr = np.ones((3, 2, 3))

In [53]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
append = np.append(new_arr, zeros, axis=0)
append

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
zeros
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [58]:
#### Delete

In [59]:
arr4 = np.random.rand(3, 2, 3)

In [60]:
arr4

array([[[0.58995802, 0.40579417, 0.74373925],
        [0.8114466 , 0.94031711, 0.55959393]],

       [[0.54154954, 0.04616293, 0.21615597],
        [0.38428648, 0.33593433, 0.19258923]],

       [[0.00480376, 0.57507214, 0.89058818],
        [0.93488383, 0.24449768, 0.81846972]]])

In [61]:
np.delete(arr4, 0, axis=1)
arr4

array([[[0.58995802, 0.40579417, 0.74373925],
        [0.8114466 , 0.94031711, 0.55959393]],

       [[0.54154954, 0.04616293, 0.21615597],
        [0.38428648, 0.33593433, 0.19258923]],

       [[0.00480376, 0.57507214, 0.89058818],
        [0.93488383, 0.24449768, 0.81846972]]])

In [62]:
arr5 = np.delete(arr4, 0, axis=1)

In [63]:
arr5

array([[[0.8114466 , 0.94031711, 0.55959393]],

       [[0.38428648, 0.33593433, 0.19258923]],

       [[0.93488383, 0.24449768, 0.81846972]]])